### ISSUE TITLE
tvOS 9.1 beta 2 build errors

### ISSUE THREAD

**Issue by arvinkx** [robreuss/VirtualGameController#1]
Hi, I am having issues getting the sample application to build for tvOS 9.1 beta 2 - it builds for iOS/OSX but I get the following errors with tvOS, any ideas? The unknown OS is in reference to the "os(WatchOS)" lines.
![screen shot 2015-11-14 at 1 32 04 pm](https://cloud.githubusercontent.com/assets/10109829/11165944/a4b3d31a-8ad4-11e5-8d04-f9ea32713ced.png)

**Comment by robreuss** [comment]
Can you add a tvOS 9.0 simulator and run it there and see if it gives the errors?  I'm downloading the beta now myself to see if I can reproduce the issue.

**Comment by arvinkx** [comment]
Yeah, I was able to get it to run on 9.0 without a problem.

**Comment by robreuss** [comment]
I was able to reproduce on tvOS 9.1 beta 2.  Looks like because the MicroGamepad supports a sub-set of the motion profile, they've marked the unsupported inputs as unavailable.  I want to be able to support the complete Device Motion set, because I support all four motion values with software controllers, so I'll need to figure out a strategy that doesn't just involve marking attitude and rotation rate not to be compiled for tvOS.  Should be able to get a fix done tomorrow.

**Comment by robreuss** [comment]
This is fixed.
